import test from 'node:test';
import assert from 'node:assert/strict';
import { applyCommand, viewState, archiveExpired } from '../lib/domain.ts';
import { createDemoState } from '../lib/demo.ts';
import type { AppState, Command } from '../lib/types.ts';
const before = (s: AppState) => new Date(new Date(s.events[0].deadline).getTime()-1000);
const save = (s: AppState, extra: Record<string,unknown> = {}) => ({ type:'registration.save',eventId:s.events[0].id,groupId:'group-1',attendees:['김은종','친구','아이'],quantities:{bibimbap:2},...extra }) as Command;
const apply = (s: AppState, c = save(s)) => applyCommand(s,s.users[0],c,before(s));
test('pure, one submission, explicit attendee count independent of meal count',()=>{const s=createDemoState(),original=structuredClone(s),n=apply(s);assert.deepEqual(s,original);assert.equal(n.registrations[0].attendees.length,3);assert.equal(n.registrations[0].items[0].quantity,2);assert.equal(n.registrations[0].applicantName,'김은종');assert.equal(apply(n).registrations.length,1);});
test('live role prevents escalation and cross-account mutation',()=>{const s=createDemoState();assert.throws(()=>applyCommand(s,{...s.users[0],role:'admin'},{type:'user.role',userId:s.users[0].id,role:'admin'}),/관리자/);assert.throws(()=>apply(s,save(s,{userId:'demo-friend'})),/다른 사람/);assert.throws(()=>apply(s,{type:'event.save',event:s.events[0]}),/리더/);assert.throws(()=>applyCommand(s,{id:'missing',name:'x',role:'admin'},save(s)),/로그인/);});
test('deadline exact boundary enforced; closed staff correction audited',()=>{const s=createDemoState(),at=new Date(s.events[0].deadline);assert.throws(()=>applyCommand(s,s.users[0],save(s),at),/마감/);const n=applyCommand(s,s.users[1],save(s,{userId:s.users[0].id}),at);assert.equal(n.registrations.length,1);assert.match(n.audits[0].detail,/"staffOverride":true/);assert.throws(()=>applyCommand(n,n.users[0],{type:'registration.cancel',eventId:n.events[0].id},at),/마감/);});
test('switch replaces menu and resets paid; invalid replacement leaves previous intact',()=>{let s=apply(createDemoState());s=applyCommand(s,s.users[1],{type:'registration.paid',registrationId:s.registrations[0].id,paid:true});const n=apply(s,save(s,{groupId:'group-3',quantities:{}}));assert.equal(n.registrations.length,1);assert.equal(n.registrations[0].groupId,'group-3');assert.deepEqual(n.registrations[0].items,[]);assert.equal(n.registrations[0].paid,false);assert.throws(()=>apply(s,save(s,{groupId:'group-2'})),/메뉴/);assert.equal(s.registrations[0].groupId,'group-1');});
test('snapshots survive price/name edits; changed quantity resets payment',()=>{let s=apply(createDemoState());s=applyCommand(s,s.users[1],{type:'registration.paid',registrationId:s.registrations[0].id,paid:true});const e=structuredClone(s.events[0]);e.groups[0].menus[0].price=10000;e.groups[0].menus[0].name='새 이름';s=applyCommand(s,s.users[1],{type:'event.save',event:e});s=apply(s);assert.equal(s.registrations[0].items[0].price,9000);assert.equal(s.registrations[0].items[0].name,'비빔밥');assert.equal(s.registrations[0].paid,true);assert.equal(apply(s,save(s,{quantities:{bibimbap:3}})).registrations[0].paid,false);});
test('removed items retained/reduced but never increased or newly selected',()=>{let s=apply(createDemoState());const e=structuredClone(s.events[0]);e.groups[0].menus=[];s=applyCommand(s,s.users[1],{type:'event.save',event:e});assert.equal(apply(s,save(s,{quantities:{bibimbap:1}})).registrations[0].items[0].quantity,1);assert.throws(()=>apply(s,save(s,{quantities:{bibimbap:3}})),/선택/);assert.throws(()=>applyCommand(s,s.users[3],save(s),before(s)),/메뉴/);});
test('runtime validation of malformed fields, quantity bounds, name limits',()=>{const s=createDemoState();for(const quantity of [-1,0.5,Infinity,NaN,101,'2',null])assert.throws(()=>apply(s,save(s,{quantities:{bibimbap:quantity}})));for(const attendees of [[],[''],['x'.repeat(51)],Array(31).fill('name'),null])assert.throws(()=>apply(s,save(s,{attendees})));assert.throws(()=>apply(s,save(s,{quantities:{unknown:1}})));assert.throws(()=>applyCommand(s,s.users[0],null as unknown as Command));});
test('protect occupied groups and validate event dates, prices, leader and photo',()=>{const s=apply(createDemoState());const mutate=(fn:(e:AppState['events'][number])=>void)=>{const e=structuredClone(s.events[0]);fn(e);return()=>applyCommand(s,s.users[1],{type:'event.save',event:e});};assert.throws(mutate(e=>{e.groups=[];}),/삭제/);assert.throws(mutate(e=>{e.groups[0].mode='attendance';}),/방식/);assert.throws(mutate(e=>{e.date='2026-02-30';}));assert.throws(mutate(e=>{e.deadline='2099-01-01T12:15:00+09:00';}));assert.throws(mutate(e=>{e.groups[0].menus[0].price=1.1;}));assert.throws(mutate(e=>{e.groups[0].photoUrl='https://evil.example/a.jpg';}));assert.throws(mutate(e=>{e.groups[0].leaderId=s.users[0].id;}));});
test('template updates isolated from weekly snapshots',()=>{const s=createDemoState(),t=structuredClone(s.templates[0]);t.menus[0].price=500;const n=applyCommand(s,s.users[1],{type:'template.save',template:t});assert.equal(n.events[0].groups[0].menus[0].price,9000);});
test('role assignment admin-only; last admin and assigned leaders protected',()=>{const s=createDemoState();assert.throws(()=>applyCommand(s,s.users[1],{type:'user.role',userId:s.users[0].id,role:'admin'}),/관리자/);assert.throws(()=>applyCommand(s,s.users[2],{type:'user.role',userId:s.users[2].id,role:'viewer'}),/마지막/);assert.throws(()=>applyCommand(s,s.users[2],{type:'user.role',userId:s.users[1].id,role:'viewer'}),/담당/);assert.equal(applyCommand(s,s.users[2],{type:'user.role',userId:s.users[0].id,role:'editor'}).users[0].role,'editor');});
test('privacy filters own orders and hides draft events, audits and templates',()=>{let s=createDemoState();s=applyCommand(s,s.users[1],save(s,{userId:'demo-friend'}),before(s));const v=viewState(s,{...s.users[0],role:'admin'});assert.equal(v.registrations.length,0);assert.equal(v.templates.length,0);assert.equal(v.audits.length,0);assert.equal(v.users.some(u=>u.id==='demo-friend'),false);assert.deepEqual(viewState(s,null),{users:[],events:[],registrations:[],templates:[],audits:[]});s.events[0].published=false;assert.equal(viewState(s,s.users[0]).events.length,0);assert.throws(()=>apply(s),/모임/);});
test('real Kakao IDs support staff edits and role changes; audit omits names and account payloads',()=>{const s=createDemoState();s.users[0].id='kakao:123456789';let n=applyCommand(s,s.users[1],save(s,{userId:s.users[0].id}),before(s));assert.equal(n.registrations[0].userId,s.users[0].id);n=applyCommand(n,n.users[2],{type:'user.role',userId:s.users[0].id,role:'editor'});assert.equal(n.users[0].role,'editor');assert.equal(n.audits.some(a=>a.detail.includes('김은종')),false);});
test('uncompleted display-name onboarding prevents ordering',()=>{const s=createDemoState();s.users[0].name='';assert.throws(()=>apply(s),/텍스트/);});

test('events may fall on any weekday with an earlier cutoff, but not after the event date',()=>{const s=apply(createDemoState());const save=(fn:(e:AppState['events'][number])=>void)=>{const e=structuredClone(s.events[0]);e.id='retreat';fn(e);return applyCommand(s,s.users[1],{type:'event.save',event:e});};const n=save(e=>{e.date='2026-08-14';e.deadline='2026-08-10T21:00:00+09:00';});assert.equal(n.events.find(x=>x.id==='retreat')?.date,'2026-08-14');assert.throws(()=>save(e=>{e.date='2026-08-14';e.deadline='2026-08-15T00:30:00+09:00';}),/마감/);});

test('restaurant links must be https and default bank details stay private to staff',()=>{const s=createDemoState(),leader=s.users[1],member=s.users[0];const t=(link:string)=>applyCommand(s,leader,{type:'template.save',template:{id:'t_link',name:'링크 식당',description:'',photoUrl:'',link,menus:[]}});assert.equal(t('https://naver.me/abc').templates.find(x=>x.id==='t_link')?.link,'https://naver.me/abc');assert.equal(t('').templates.find(x=>x.id==='t_link')?.link,'');assert.throws(()=>t('http://example.com'),/https/);assert.throws(()=>t('javascript:alert(1)'));const bank={bank:'국민',account:'123-456',holder:'김현아'};const n=applyCommand(s,leader,{type:'profile.bank',bank});assert.deepEqual(n.users.find(u=>u.id===leader.id)?.bank,bank);assert.throws(()=>applyCommand(s,member,{type:'profile.bank',bank}),/리더/);assert.equal(viewState(n,member).users.some(u=>u.bank),false);});

test('an event cannot be published without any restaurant',()=>{const s=createDemoState(),e=structuredClone(s.events[0]);e.id='empty';e.date='2026-11-01';e.deadline='2026-11-01T03:15:00.000Z';e.groups=[];assert.throws(()=>applyCommand(s,s.users[1],{type:'event.save',event:e}),/식당/);e.published=false;assert.ok(applyCommand(s,s.users[1],{type:'event.save',event:e}).events.some(x=>x.id==='empty'));});

test('several meals may share one date, each with its own registrations',()=>{const s=createDemoState(),e=structuredClone(s.events[0]);e.id='dinner';e.title='저녁 식사';const n=applyCommand(s,s.users[1],{type:'event.save',event:e});assert.equal(n.events.filter(x=>x.date===e.date).length,2);});

test('a meal with signups cannot be deleted, an empty one can, and only staff may delete',()=>{const s=createDemoState(),member=s.users[0],leader=s.users[1],ev=s.events[0],g=ev.groups[0];const signed=applyCommand(s,member,{type:'registration.save',eventId:ev.id,groupId:g.id,attendees:['김은종'],quantities:g.mode==='order'?{[g.menus[0].id]:1}:{}},new Date(0));assert.throws(()=>applyCommand(signed,leader,{type:'event.delete',eventId:ev.id}),/신청한 분이 1명/);assert.throws(()=>applyCommand(signed,member,{type:'event.delete',eventId:ev.id}),/리더/);const extra=structuredClone(ev);extra.id='extra';extra.groups=[];extra.published=false;const withExtra=applyCommand(signed,leader,{type:'event.save',event:extra});const removed=applyCommand(withExtra,leader,{type:'event.delete',eventId:'extra'});assert.equal(removed.events.some(x=>x.id==='extra'),false);assert.equal(removed.events.some(x=>x.id===ev.id),true);});

test('meals move to the archive 7+ days after the date once every order is settled; stored data is untouched',()=>{const s=createDemoState(),ev=s.events[0],g=ev.groups.find(x=>x.mode==='order')!;const eventDay=Date.parse(`${ev.date}T12:00:00+09:00`),day=86400000;
const signed=applyCommand(s,s.users[0],{type:'registration.save',eventId:ev.id,groupId:g.id,attendees:['김은종'],quantities:{[g.menus[0].id]:1}},new Date(0));
// within 7 days: kept even if paid
const paid=applyCommand(signed,s.users[1],{type:'registration.paid',registrationId:signed.registrations[0].id,paid:true},new Date(0));
assert.deepEqual(archiveExpired(paid,new Date(eventDay+7*day)).archived,[]);
// 8+ days later but unpaid: kept
assert.deepEqual(archiveExpired(signed,new Date(eventDay+9*day)).archived,[]);
// 8+ days later and paid: removed with its signups
const out=archiveExpired(paid,new Date(eventDay+9*day));assert.deepEqual(out.archived,[ev.id]);assert.equal(out.state.events.some(e=>e.id===ev.id),false);assert.equal(out.state.registrations.some(r=>r.eventId===ev.id),false);assert.equal(paid.registrations.some(r=>r.eventId===ev.id),true);assert.equal(archiveExpired({...paid,events:paid.events.map(e=>({...e,archived:true}))},new Date(eventDay+9*day)).archived.length,0);
// no signups at all: removed after the week
assert.deepEqual(archiveExpired(s,new Date(eventDay+9*day)).archived.includes(ev.id),true);
// upcoming meals are never removed
assert.deepEqual(archiveExpired(paid,new Date(eventDay-2*day)).archived,[]);});

test('staff can delete a saved restaurant without touching meals already made from it, members cannot',()=>{const s=createDemoState(),leader=s.users[1],member=s.users[0],tpl=s.templates[0];assert.throws(()=>applyCommand(s,member,{type:'template.delete',templateId:tpl.id}),/리더/);const n=applyCommand(s,leader,{type:'template.delete',templateId:tpl.id});assert.equal(n.templates.some(x=>x.id===tpl.id),false);assert.equal(n.events.length,s.events.length);assert.deepEqual(n.events[0].groups.map(g=>g.name),s.events[0].groups.map(g=>g.name));assert.throws(()=>applyCommand(n,leader,{type:'template.delete',templateId:tpl.id}),/찾을 수/);});

test('paid signups cannot be cancelled, and church-supported meals carry no bank details or payment tracking',()=>{const s=createDemoState(),member=s.users[0],leader=s.users[1],ev=s.events[0],g=ev.groups.find(x=>x.mode==='order')!;
const signed=applyCommand(s,member,{type:'registration.save',eventId:ev.id,groupId:g.id,attendees:['김은종'],quantities:{[g.menus[0].id]:1}},new Date(0));
const paid=applyCommand(signed,leader,{type:'registration.paid',registrationId:signed.registrations[0].id,paid:true},new Date(0));
assert.throws(()=>applyCommand(paid,member,{type:'registration.cancel',eventId:ev.id},new Date(0)),/입금이 확인된/);
assert.throws(()=>applyCommand(paid,leader,{type:'registration.cancel',eventId:ev.id,userId:member.id},new Date(0)),/입금이 확인된/);
const unpaid=applyCommand(paid,leader,{type:'registration.paid',registrationId:signed.registrations[0].id,paid:false},new Date(0));
assert.equal(applyCommand(unpaid,member,{type:'registration.cancel',eventId:ev.id},new Date(0)).registrations.length,0);
const church=structuredClone(ev);church.id='church';church.date='2027-01-03';church.deadline='2027-01-03T03:15:00.000Z';church.groups=church.groups.map((x,i)=>({...x,id:'c'+i,churchPaid:true,payment:{bank:'국민',account:'111',holder:'김'}}));
const saved=applyCommand(s,leader,{type:'event.save',event:church});const cg=saved.events.find(e=>e.id==='church')!.groups[0];
assert.equal(cg.churchPaid,true);assert.deepEqual(cg.payment,{bank:'',account:'',holder:''});
const cgOrder=cg.mode==='order'?cg:saved.events.find(e=>e.id==='church')!.groups.find(x=>x.mode==='order')!;
const reg=applyCommand(saved,member,{type:'registration.save',eventId:'church',groupId:cgOrder.id,attendees:['김은종'],quantities:{[cgOrder.menus[0].id]:1}},new Date(0));
assert.throws(()=>applyCommand(reg,leader,{type:'registration.paid',registrationId:reg.registrations[0].id,paid:true},new Date(0)),/교회 지원/);
assert.deepEqual(archiveExpired(reg,new Date(Date.parse('2027-01-20T00:00:00+09:00'))).archived.includes('church'),true);});

test('saving a meal keeps it active (archived=false) and new audit ids are unique without loading history',()=>{const s=createDemoState(),e=structuredClone(s.events[0]);const n=applyCommand({...s,audits:[]},s.users[1],{type:'event.save',event:e});assert.equal(n.events.find(x=>x.id===e.id)?.archived,false);const m=applyCommand({...n,audits:[]},s.users[1],{type:'event.save',event:e});assert.notEqual(n.audits[0].id,m.audits[0].id);});
